### ISSUE TITLE
Broken Rainbow mod

### ISSUE THREAD

**Issue by davegenie** [darknight1050/RainbowMod#2]
Hi Mate,  
Very Sorry the private message. 

Do hope you keeping well in this pandemic.

Just wanted to reach out and say I absolutely loved your mod you did for the rainbow lights on the quest and wondered if you would be releasing this again for the Quest 2 at any point, Beat Saber is just not the same without your Mod.

Fully understand if you are busy and not in the mood to do this now but Just wondered if this was something you planned to complete in the future. 

thanks again for all your hard work. 

You Genius.

Dave

**Comment by davegenie** [comment]
Sorry rude of me to ask this way.

**Comment by darknight1050** [comment]
Thank you for the kind words.
I will definitely update RainbowMod but I don't know how long it will take me.

**Comment by davegenie** [comment]
Hi mate.

Hope you keeping well.

I wondered if you had any more thought on making your great Rainbow mod
work on the Quest 2.

Just not the same without it.

Thanks

Dave

**Comment by darknight1050** [comment]
Hey
Currently I'm working on other mods but I might update it when I have more time
